### PR TITLE
Fix Component.start result type with @context_teardown

### PR DESCRIPTION
**Pull request by davidbrochart**
Follow-up #68.

### CODE REVIEW

**Comment by davidbrochart** [comment]
Note that Python 3.8 yield this error:
```py
    class MyComponent(Component):
        @context_teardown
        async def start(
            self,
            ctx: Context,
>       ) -> AsyncGenerator[None, BaseException | None]:
E       TypeError: 'ABCMeta' object is not subscriptable
```

**Comment by agronholm** [comment]
That happens without `from __future__ import annotations` because the collection ABCs were not generic before Python 3.9.

**Comment by davidbrochart** [comment]
Oh, thanks!

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
