### PR TITLE
Keep a reference to tasks

### PR DESCRIPTION
**Pull request by davidbrochart**
Tasks may disappear while executing because of garbage collection. See [the documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task):

image

### CODE REVIEW

**Comment by agronholm** [comment]
I think this needs a new test to ensure that tasks don't get dropped.

**Comment by davidbrochart** [comment]
I think this test is enough, since the coroutine callback doesn't hold any reference to an outside object, and only has a side effect. But it is very unlikely to fail even without this PR, because it will probably not be garbage collected anyway.

**Comment by agronholm** [comment]
The basic requirement for any fix PR is to demonstrate that the change does in fact fix a problem. CPython should be very consistent in this manner, meaning that once the references to an object drop to zero, it's immediately gc'd. If you can't demonstrate this behavior, then what does this actually fix?

**Comment by davidbrochart** [comment]
Right.
I've been trying to trigger the bug without this PR, using `gc.collect()`, but I cannot. I think the task cannot be garbage-collected because of its reference to the event.
Should we close this PR then?

**Comment by agronholm** [comment]
I think so. If the event system was dropping tasks, I, you or someone else would probably have noticed it before.

**Pull request closed without merging**
