### PR TITLE
Add missing self in docs, more types

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by agronholm** [comment]
The proper return type would be `collections.abc.AsyncGenerator[None, BaseException | None]`, yes?

**Comment by davidbrochart** [comment]
I can send a PR, maybe using `Optional` instead of `|None`?

**Comment by agronholm** [comment]
The latter is preferred.

**Comment by davidbrochart** [comment]
Isn't it for Python >=3.10 ?

**Comment by agronholm** [comment]
Works fine on older Pythons if you add `from __future__ import annotations`.

**Pull request merged**
